source "https://rubygems.org"

ruby '2.3.1'

group :test, :development do
gem 'rspec'
gem 'rspec-sinatra'
gem 'dm-postgres-adapter'
gem 'capybara'
gem 'database_cleaner'
end

gem 'data_mapper'
gem 'sinatra'
gem 'rake'
gem 'bcrypt'
gem 'sinatra-flash'
gem 'pry'
